- name: create Prometheus user 
  user:
    name: prometheus
    shell: /bin/false
    createhome: no

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    "{{ prometheusDirectories }}"


- name: find if downloaded file exist
  stat:
    path: "{{ prometheusDownloadingPath }}"
  register: _file_exists


- name: Download prometheus
  get_url:
    url: "{{ prometheusDownloadLink }}"
    dest: "{{ prometheusDownloadingPath }}"
  when: _file_exists.stat.exists == false


- name: untar prometheus installer 
  unarchive:
    src: "{{ prometheusDownloadingPath }}"
    dest: /tmp/
    remote_src: true
  when: _file_exists.stat.exists == false


- name: find if console directores if exist 
  stat:
    path: /tmp/prometheus-2.35.0.linux-amd64/console*
  register: directories_exists


- name: Move console files to /etc/prometheus
  shell: mv /tmp/prometheus-2.35.0.linux-amd64/console* /etc/prometheus/
  when: directories_exists.stat.exists == true


- name: find if prometheus.yml file if exist 
  stat:
    path: /tmp/prometheus-2.35.0.linux-amd64/prometheus.yml
  register: prometheusFile_exists


- name: Move prometheus configuration file to /etc/prometheus
  shell: mv /tmp/prometheus-2.35.0.linux-amd64/prometheus.yml /etc/prometheus
  when: prometheusFile_exists.stat.exists == true



- name: Change prometheus configuration directory ownership
  file:
    path: /etc/prometheus
    owner: prometheus
    group: prometheus


- name: find if prometheus binary if exist 
  stat:
    path: /tmp/prometheus-2.35.0.linux-amd64/prometheus
  register: prometheusBinary_exists


- name: Move prometheus to /usr/local/bin/
  shell: mv /tmp/prometheus-2.35.0.linux-amd64/prometheus /usr/local/bin/
  when: prometheusBinary_exists.stat.exists == true


- name: find if promtool binary if exist 
  stat:
    path: /tmp/prometheus-2.35.0.linux-amd64/promtool 
  register: promtoolBinary_exists


- name: Move promtool to /usr/local/bin/
  shell: mv /tmp/prometheus-2.35.0.linux-amd64/promtool /usr/local/bin/
  when: promtoolBinary_exists.stat.exists == true


- name: change prometheus directories ownership
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
  with_items:
    "{{ prometheusBinDirectories }}"


- name: make prometheus as a service 
  copy: 
    src: ./prometheus.service
    dest: "{{ prometheusServiceFilePath }}"
    owner: prometheus
    group: prometheus


- name: Reload systemd configuration
  systemd:
    daemon_reload: yes


- name: start prometheus service 
  systemd:
    name: prometheus
    state: started
    enabled: true